### ISSUE TITLE
RuntimeError: expected scalar type Long but found Float

### ISSUE THREAD

**Issue by jmtingz** [PointSite/PointSite#2]
environments: torch 1.10.2+cu113
execute  python setup_test.py
got errors as shown below:
Traceback (most recent call last):
  File "setup_test.py", line 64, in <module>
    output = model(input)
  File "/home/zhangjm/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhangjm/.local/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/zhangjm/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhangjm/.local/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/zhangjm/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhangjm/pipeline/pointsite/PointSite/sparseconvnet/maxPooling.py", line 96, in forward
    self.nFeaturesToDrop)
  File "/home/zhangjm/pipeline/pointsite/PointSite/sparseconvnet/maxPooling.py", line 39, in forward
    nFeaturesToDrop)
RuntimeError: expected scalar type Long but found Float

**Comment by jiaxin-ustc** [comment]
I met the same issue when i try to, ”python setup_test.py“ seems actually test whether sparseconvnet module install succeed. I solve this issue through immediately through SparseConvNet repo instructions(https://github.com/facebookresearch/SparseConvNet). And in this process, may need add cuda lib path to ~/.bashrc
export LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64:$LD_LIBRARY_PATH
export CUDA_HOME=/usr/local/cuda
Hope useful.

**Comment by ltl888** [comment]
> 当我尝试时遇到了同样的问题，“python setup_test.py”似乎实际上是测试 sparseconvnet 模块安装是否成功。我立即通过 SparseConvNet repo instructions（https://github.com/facebookresearch/SparseConvNet） 解决了这个问题。而在这个过程中，可能需要添加 cuda lib 路径到 ~/.bashrc export LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64：$LD_LIBRARY_PATH export CUDA_HOME=/usr/local/cuda 希望有用。

 您好，我在尝试中也遇到expected scalar type Long but found Float的问题，再尝试过您的方法：添加 cuda lib 路径到 ~/.bashrc
export LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64：$LD_LIBRARY_PATH
export CUDA_HOME=/usr/local/cuda
后，问题仍然存在。
$ python inference.py --output blind_out --data example/blind --select_list example/blind_list
Inference examples: 81
#classifer parameters: 2689644
Load model model
  0%|                                                                                                                           | 0/81 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 243, in <module>
    main(args)
  File "inference.py", line 197, in main
    random_seed=args.seed)
  File "inference.py", line 140, in predict_binding_site
    predictions = classifier([chain_coords_news, chain_features])
  File "/home/malab21/disk3/protein_design/0.micromamba/envs/pointsite/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "model/unet.py", line 26, in forward
    x=self.sparseModel(x)
  File "/home/malab21/disk3/protein_design/0.micromamba/envs/pointsite/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/malab21/disk3/protein_design/0.micromamba/envs/pointsite/lib/python3.6/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/malab21/disk3/protein_design/0.micromamba/envs/pointsite/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/malab21/disk3/protein_design/0.micromamba/envs/pointsite/lib/python3.6/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/malab21/disk3/protein_design/0.micromamba/envs/pointsite/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/malab21/disk3/protein_design/PointSite/sparseconvnet/tables.py", line 48, in forward
    return [module(input) for module in self._modules.values()]
  File "/home/malab21/disk3/protein_design/PointSite/sparseconvnet/tables.py", line 48, in <listcomp>
    return [module(input) for module in self._modules.values()]
  File "/home/malab21/disk3/protein_design/0.micromamba/envs/pointsite/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/malab21/disk3/protein_design/0.micromamba/envs/pointsite/lib/python3.6/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/malab21/disk3/protein_design/0.micromamba/envs/pointsite/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/malab21/disk3/protein_design/PointSite/sparseconvnet/convolution.py", line 48, in forward
    self.filter_stride)
  File "/home/malab21/disk3/protein_design/PointSite/sparseconvnet/convolution.py", line 104, in forward
    bias)
RuntimeError: expected scalar type Long but found Float

想问一下您当时还用了什么方法来解决这个问题吗

**Comment by jiaxin-ustc** [comment]
不使用PyTorch 1.3 GPU版本，直接使用CPU版本。&nbsp;


畅想天空
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月19日(星期四) 下午5:25
收件人: "PointSite/PointSite";
抄送: "Comment";
主题: Re: [PointSite/PointSite] RuntimeError: expected scalar type Long but found Float (Issue #2)





  
当我尝试时遇到了同样的问题，“python setup_test.py”似乎实际上是测试 sparseconvnet 模块安装是否成功。我立即通过 SparseConvNet repo instructions（https://github.com/facebookresearch/SparseConvNet） 解决了这个问题。而在这个过程中，可能需要添加 cuda lib 路径到 ~/.bashrc export LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64：$LD_LIBRARY_PATH export CUDA_HOME=/usr/local/cuda 希望有用。
  
您好，我在尝试中也遇到expected scalar type Long but found Float的问题，再尝试过您的方法：添加 cuda lib 路径到 ~/.bashrc
 export LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64：$LD_LIBRARY_PATH
 export CUDA_HOME=/usr/local/cuda
 后，问题仍然存在。
 $ python inference.py --output blind_out --data example/blind --select_list example/blind_list
 Inference examples: 81
 #classifer parameters: 2689644
 Load model model
 0%|                                                                                                                           | 0/81 [00:00<?, ?it/s]
 Traceback (most recent call last):
 File "inference.py", line 243, in 
 main(args)
 File "inference.py", line 197, in main
 random_seed=args.seed)
 File "inference.py", line 140, in predict_binding_site
 predictions = classifier([chain_coords_news, chain_features])
 File "/home/malab21/disk3/protein_design/0.micromamba/envs/pointsite/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
 return forward_call(*input, **kwargs)
 File "model/unet.py", line 26, in forward
 x=self.sparseModel(x)
 File "/home/malab21/disk3/protein_design/0.micromamba/envs/pointsite/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
 return forward_call(*input, **kwargs)
 File "/home/malab21/disk3/protein_design/0.micromamba/envs/pointsite/lib/python3.6/site-packages/torch/nn/modules/container.py", line 141, in forward
 input = module(input)
 File "/home/malab21/disk3/protein_design/0.micromamba/envs/pointsite/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
 return forward_call(*input, **kwargs)
 File "/home/malab21/disk3/protein_design/0.micromamba/envs/pointsite/lib/python3.6/site-packages/torch/nn/modules/container.py", line 141, in forward
 input = module(input)
 File "/home/malab21/disk3/protein_design/0.micromamba/envs/pointsite/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
 return forward_call(*input, **kwargs)
 File "/home/malab21/disk3/protein_design/PointSite/sparseconvnet/tables.py", line 48, in forward
 return [module(input) for module in self._modules.values()]
 File "/home/malab21/disk3/protein_design/PointSite/sparseconvnet/tables.py", line 48, in 
 return [module(input) for module in self._modules.values()]
 File "/home/malab21/disk3/protein_design/0.micromamba/envs/pointsite/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
 return forward_call(*input, **kwargs)
 File "/home/malab21/disk3/protein_design/0.micromamba/envs/pointsite/lib/python3.6/site-packages/torch/nn/modules/container.py", line 141, in forward
 input = module(input)
 File "/home/malab21/disk3/protein_design/0.micromamba/envs/pointsite/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
 return forward_call(*input, **kwargs)
 File "/home/malab21/disk3/protein_design/PointSite/sparseconvnet/convolution.py", line 48, in forward
 self.filter_stride)
 File "/home/malab21/disk3/protein_design/PointSite/sparseconvnet/convolution.py", line 104, in forward
 bias)
 RuntimeError: expected scalar type Long but found Float
 
想问一下您当时还用了什么方法来解决这个问题吗
 
&mdash;
