### ISSUE TITLE
Can't install PointSite

### ISSUE THREAD

**Issue by JavierSanchez-Utges** [PointSite/PointSite#8]
I am running into installation errors: `ImportError: /content/PointSite/sparseconvnet/SCN.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv`

It would be great if you could provide a Colab Notebook where you can run PointSite or a docker image. Thanks!

**Comment by JavierSanchez-Utges** [comment]
This is the code I am running on a Colab Notebook:
```
!git clone https://github.com/PointSite/PointSite.git
%cd PointSite

!wget -c https://repo.anaconda.com/miniconda/Miniconda3-4.3.31-Linux-x86_64.sh -O miniconda.sh # downloads miniconda, runs python 3.6.3
!chmod +x miniconda.sh # adds execution permission
!bash ./miniconda.sh -b -f -p /usr/local # installs Anaconda in /usr/local 

!pip install torch==1.3.0
!pip install scikit-learn
!pip install tqdm

!rm -rf build/ dist/ sparseconvnet.egg-info sparseconvnet/SCN*.so
!python setup.py develop
!python util/setup_test.py
!rm -rf build/ dist/ sparseconvnet.egg-info

!chmod +x ./util/PDB_Tool
!chmod +x ./util/PDB_To_XYZ
!python inference.py
```

Note I used a specific miniconda version that runs 3.6. That Anaconda2 version suggested in the README uses python2.7 and also was giving errors.

With this script, this is the error I get:

```
Traceback (most recent call last):
  File "inference.py", line 2, in <module>
    import sparseconvnet as scn
  File "/content/PointSite/sparseconvnet/__init__.py", line 10, in <module>
    from .add import Add_fun, Add2_fun
  File "/content/PointSite/sparseconvnet/add.py", line 7, in <module>
    from .utils import add_feature_planes
  File "/content/PointSite/sparseconvnet/utils.py", line 9, in <module>
    from .metadata import Metadata
  File "/content/PointSite/sparseconvnet/metadata.py", line 14, in <module>
    import sparseconvnet.SCN
ImportError: /content/PointSite/sparseconvnet/SCN.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv
```

**Comment by HongjiaL** [comment]
I have encountered the same problem, have you solved it?

**Comment by JavierSanchez-Utges** [comment]
Hi, @HongjiaL. No, I could never install nor use PointSite. However, if you are interested in ligand binding site prediction tools, you can check our paper, in which we conducted the largest benchmark of ligand site prediction tools to date. You can find it [here](https://doi.org/10.1186/s13321-024-00923-z). I hope this helps and good luck!
